// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const ContentPolicyEventListRequest: core.serialization.Schema<
    serializers.ContentPolicyEventListRequest.Raw,
    Omit<Zep.ContentPolicyEventListRequest, "limit" | "cursor">
> = core.serialization.object({
    filters: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace ContentPolicyEventListRequest {
    export interface Raw {
        filters?: Record<string, unknown> | null;
    }
}
