/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as Zep from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import { Reranker } from "../../../../types/Reranker.js";
import { GraphSearchScope } from "../../../../types/GraphSearchScope.js";
import { SearchFilters } from "../../../../types/SearchFilters.js";

export const GraphSearchQuery: core.serialization.Schema<serializers.GraphSearchQuery.Raw, Zep.GraphSearchQuery> =
    core.serialization.object({
        bfsOriginNodeUuids: core.serialization.property(
            "bfs_origin_node_uuids",
            core.serialization.list(core.serialization.string()).optional(),
        ),
        centerNodeUuid: core.serialization.property("center_node_uuid", core.serialization.string().optional()),
        graphId: core.serialization.property("graph_id", core.serialization.string().optional()),
        limit: core.serialization.number().optional(),
        minFactRating: core.serialization.property("min_fact_rating", core.serialization.number().optional()),
        minScore: core.serialization.property("min_score", core.serialization.number().optional()),
        mmrLambda: core.serialization.property("mmr_lambda", core.serialization.number().optional()),
        query: core.serialization.string(),
        reranker: Reranker.optional(),
        scope: GraphSearchScope.optional(),
        searchFilters: core.serialization.property("search_filters", SearchFilters.optional()),
        userId: core.serialization.property("user_id", core.serialization.string().optional()),
    });

export declare namespace GraphSearchQuery {
    export interface Raw {
        bfs_origin_node_uuids?: string[] | null;
        center_node_uuid?: string | null;
        graph_id?: string | null;
        limit?: number | null;
        min_fact_rating?: number | null;
        min_score?: number | null;
        mmr_lambda?: number | null;
        query: string;
        reranker?: Reranker.Raw | null;
        scope?: GraphSearchScope.Raw | null;
        search_filters?: SearchFilters.Raw | null;
        user_id?: string | null;
    }
}
