export { EntityTypeRequest } from "./EntityTypeRequest.js";
export { AddDataRequest } from "./AddDataRequest.js";
export { AddDataBatchRequest } from "./AddDataBatchRequest.js";
export { AddTripleRequest } from "./AddTripleRequest.js";
export { CloneGraphRequest } from "./CloneGraphRequest.js";
export { CreateGraphRequest } from "./CreateGraphRequest.js";
export { GraphSearchQuery } from "./GraphSearchQuery.js";
export { UpdateGraphRequest } from "./UpdateGraphRequest.js";
export { GraphSetOntologyRequest } from "./GraphSetOntologyRequest.js";
