// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";
import { DerivedNode } from "../../../../../types/DerivedNode.js";

export const Response: core.serialization.Schema<
    serializers.graph.observation.getByGraphId.Response.Raw,
    Zep.DerivedNode[]
> = core.serialization.list(DerivedNode);

export declare namespace Response {
    export type Raw = DerivedNode.Raw[];
}
