// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { AgentMemorySettings } from "../../../../types/AgentMemorySettings.js";

export const PatchAgentRequest: core.serialization.Schema<serializers.PatchAgentRequest.Raw, Zep.PatchAgentRequest> =
    core.serialization.object({
        deploymentId: core.serialization.property("deployment_id", core.serialization.string().optionalNullable()),
        description: core.serialization.string().optionalNullable(),
        expectedRevision: core.serialization.property("expected_revision", core.serialization.number()),
        memorySettings: core.serialization.property("memory_settings", AgentMemorySettings.optional()),
        metadata: core.serialization
            .record(core.serialization.string(), core.serialization.unknown())
            .optionalNullable(),
        name: core.serialization.string().optionalNullable(),
        version: core.serialization.string().optionalNullable(),
    });

export declare namespace PatchAgentRequest {
    export interface Raw {
        deployment_id?: (string | null | undefined) | null;
        description?: (string | null | undefined) | null;
        expected_revision: number;
        memory_settings?: AgentMemorySettings.Raw | null;
        metadata?: (Record<string, unknown> | null | undefined) | null;
        name?: (string | null | undefined) | null;
        version?: (string | null | undefined) | null;
    }
}
