/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Zep from "../../../../api";
import * as core from "../../../../core";
import { CreateDocumentRequest } from "../../../types/CreateDocumentRequest";

export const Request: core.serialization.Schema<
    serializers.document.createMultiple.Request.Raw,
    Zep.CreateDocumentRequest[]
> = core.serialization.list(CreateDocumentRequest);

export declare namespace Request {
    type Raw = CreateDocumentRequest.Raw[];
}

export const Response: core.serialization.Schema<serializers.document.createMultiple.Response.Raw, string[]> =
    core.serialization.list(core.serialization.string());

export declare namespace Response {
    type Raw = string[];
}
