/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Zep from "../../../../../api/index";
import * as core from "../../../../../core";
import { SearchScope } from "../../../../types/SearchScope";
import { SearchType } from "../../../../types/SearchType";

export const MemorySearchPayload: core.serialization.Schema<
    serializers.MemorySearchPayload.Raw,
    Omit<Zep.MemorySearchPayload, "limit">
> = core.serialization.object({
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    minFactRating: core.serialization.property("min_fact_rating", core.serialization.number().optional()),
    minScore: core.serialization.property("min_score", core.serialization.number().optional()),
    mmrLambda: core.serialization.property("mmr_lambda", core.serialization.number().optional()),
    searchScope: core.serialization.property("search_scope", SearchScope.optional()),
    searchType: core.serialization.property("search_type", SearchType.optional()),
    text: core.serialization.string().optional(),
});

export declare namespace MemorySearchPayload {
    interface Raw {
        metadata?: Record<string, unknown> | null;
        min_fact_rating?: number | null;
        min_score?: number | null;
        mmr_lambda?: number | null;
        search_scope?: SearchScope.Raw | null;
        search_type?: SearchType.Raw | null;
        text?: string | null;
    }
}
