/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Zep from "../../../../../api/index";
import * as core from "../../../../../core";

export const UpdateSessionRequest: core.serialization.Schema<
    serializers.UpdateSessionRequest.Raw,
    Zep.UpdateSessionRequest
> = core.serialization.object({
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace UpdateSessionRequest {
    interface Raw {
        metadata: Record<string, unknown>;
    }
}
