// This file was auto-generated by Fern from our API Definition.

import * as Zep from "../../../src/api/index";
import { ZepClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("ProjectClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [{ created_at: "2026-01-01T00:00:00Z", id: "project_123", name: "Support" }],
            next_cursor: "page-2",
        };

        server
            .mockEndpoint({ once: false })
            .get("/trace-connections/connection_uuid/projects")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            items: [
                {
                    createdAt: "2026-01-01T00:00:00Z",
                    id: "project_123",
                    name: "Support",
                },
            ],
            nextCursor: "page-2",
        };
        const page = await client.traceConnection.project.list("connection_uuid");

        expect(expected.items).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.items).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/trace-connections/connection_uuid/projects")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.traceConnection.project.list("connection_uuid");
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/trace-connections/connection_uuid/projects")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.traceConnection.project.list("connection_uuid");
        }).rejects.toThrow(Zep.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/trace-connections/connection_uuid/projects")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.traceConnection.project.list("connection_uuid");
        }).rejects.toThrow(Zep.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/trace-connections/connection_uuid/projects")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.traceConnection.project.list("connection_uuid");
        }).rejects.toThrow(Zep.NotFoundError);
    });
});
