// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ThreadListMessagesRequestOrder: core.serialization.Schema<
    serializers.ThreadListMessagesRequestOrder.Raw,
    Zep.ThreadListMessagesRequestOrder
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace ThreadListMessagesRequestOrder {
    export type Raw = "asc" | "desc";
}
