// This file was auto-generated by Fern from our API Definition.

export const NodeListNeighborsRequestOrderBy = {
    Uuid: "uuid",
    CreatedAt: "created_at",
} as const;
export type NodeListNeighborsRequestOrderBy =
    (typeof NodeListNeighborsRequestOrderBy)[keyof typeof NodeListNeighborsRequestOrderBy];
