// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../../../index.js";

/**
 * @example
 *     {
 *         body: {}
 *     }
 */
export interface HyperedgeListRequest {
    /** Page size */
    limit?: number;
    /** Opaque page cursor */
    cursor?: string;
    /** Sort key: uuid or created_at */
    orderBy?: Zep.graph.HyperedgeListRequestOrderBy;
    /** Sort direction: asc or desc */
    order?: Zep.graph.HyperedgeListRequestOrder;
    body: Zep.ArtifactListRequest;
}
