/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Zep from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GraphNodeNeighborsRequest {
    /**
     * Opaque cursor for pagination, obtained from the Zep-Next-Cursor
     * response header of the previous page.
     */
    cursor?: string;
    /**
     * Orientation of the connecting edge relative to the anchor node: "out"
     * (anchor is the edge's source), "in" (anchor is the edge's target), or
     * "both" (either). Defaults to "both".
     */
    direction?: string;
    /**
     * Sort direction for order_by. One of "asc" or "desc". Defaults to
     * "desc". Named direction_sort to avoid clashing with the traversal
     * Direction field above.
     */
    directionSort?: string;
    /**
     * Filters constraining the connecting edges (edge types, dates, and the
     * section-3 node-/episode-anchored fields) and the neighbor nodes
     * (node_labels/exclude_node_labels). Reuses the graph.search filter
     * type.
     */
    filters?: Zep.SearchFilters;
    /**
     * Maximum number of neighbor nodes to return. An explicit value is
     * clamped to 50; when omitted, the default page size (100) applies.
     */
    limit?: number;
    /**
     * Field to sort neighbor nodes by. One of "uuid" or "created_at".
     * Defaults to "uuid".
     */
    orderBy?: string;
}
