// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../../../index.js";

/**
 * @example
 *     {
 *         body: {}
 *     }
 */
export interface NodeListRequest {
    /** Page size */
    limit?: number;
    /** Opaque page cursor */
    cursor?: string;
    /** Sort key: uuid (default) or degree */
    orderBy?: Zep.graph.NodeListRequestOrderBy;
    /** Sort direction: asc or desc (default desc) */
    order?: Zep.graph.NodeListRequestOrder;
    body: Zep.ArtifactListRequest;
}
