// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";

export const NeighborsRequestDirection: core.serialization.Schema<
    serializers.graph.NeighborsRequestDirection.Raw,
    Zep.graph.NeighborsRequestDirection
> = core.serialization.enum_(["in", "out", "both"]);

export declare namespace NeighborsRequestDirection {
    export type Raw = "in" | "out" | "both";
}
