// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";

export const NodeListNeighborsRequestOrderBy: core.serialization.Schema<
    serializers.graph.NodeListNeighborsRequestOrderBy.Raw,
    Zep.graph.NodeListNeighborsRequestOrderBy
> = core.serialization.enum_(["uuid", "created_at"]);

export declare namespace NodeListNeighborsRequestOrderBy {
    export type Raw = "uuid" | "created_at";
}
