// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface UserListRequest {
    /** Page size */
    limit?: number;
    /** Opaque page cursor */
    cursor?: string;
    /** Sort field */
    orderBy?: Zep.UserListRequestOrderBy;
    /** asc or desc */
    order?: Zep.UserListRequestOrder;
    /** Filters results to users whose user ID, email, or name contains this text. */
    search?: string;
}
