/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UserListOrderedRequest {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Cursor
     */
    cursor?: number;
}
