// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../../../index.js";

/**
 * @example
 *     {
 *         data: "data"
 *     }
 */
export interface AddEpisodeRequest {
    /**
     * The episode's reference time, used for temporal reasoning rather than
     * ingestion time.
     */
    createdAt?: string;
    /** The episode content to add to the graph. */
    data: string;
    /** Groups this episode as a chunk of a document on the graph. */
    documentId?: string;
    /** Metadata to store on the episode. */
    metadata?: Record<string, unknown>;
    /** A description of the source of this episode. */
    sourceDescription?: string;
    /**
     * When true, prevents extraction of generic entity nodes that do not match
     * the configured ontology.
     */
    strictOntology?: boolean;
    /** The data format of the episode: text, json, or message. Defaults to text. */
    type?: Zep.graph.V4AddEpisodeRequestType;
}
