/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface EpisodeGetByGraphIdRequest {
    /**
     * The number of most recent episodes to retrieve.
     */
    lastn?: number;
}
