// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../../../index.js";

/**
 * @example
 *     {
 *         body: {}
 *     }
 */
export interface EpisodeListRequest {
    /** Page size */
    limit?: number;
    /** Opaque page cursor */
    cursor?: string;
    /** Sort field */
    orderBy?: Zep.graph.EpisodeListRequestOrderBy;
    /** Sort direction: asc or desc */
    order?: Zep.graph.EpisodeListRequestOrder;
    body: Zep.ArtifactListRequest;
}
