// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface PatchEpisodeRequest {
    /** Metadata to merge onto the episode; a key set to null is removed. */
    metadata?: Record<string, unknown>;
}
