// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateThreadRequest: core.serialization.Schema<
    serializers.CreateThreadRequest.Raw,
    Zep.CreateThreadRequest
> = core.serialization.object({
    threadId: core.serialization.property("thread_id", core.serialization.string().optional()),
    userUuid: core.serialization.property("user_uuid", core.serialization.string().optional()),
});

export declare namespace CreateThreadRequest {
    export interface Raw {
        thread_id?: string | null;
        user_uuid?: string | null;
    }
}
