/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Zep from "../../../../api/index";
import * as core from "../../../../core";
import { Episode } from "../../../types/Episode";

export const Response: core.serialization.Schema<serializers.graph.addBatch.Response.Raw, Zep.Episode[]> =
    core.serialization.list(Episode);

export declare namespace Response {
    export type Raw = Episode.Raw[];
}
