// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../index.js";

export interface AddNodesResult {
    /**
     * An accept-time acknowledgement of the nodes you submitted, each carrying
     * its assigned identifier and the fields you supplied, not the full stored
     * node.
     */
    nodes?: Zep.AddedNode[];
    /** The asynchronous task that tracks the nodes' extraction and indexing. */
    task?: Zep.Task;
}
