// This file was auto-generated by Fern from our API Definition.

export const AgentTrajectoryEventProcessingState = {
    Pending: "pending",
    Processing: "processing",
    Processed: "processed",
    Failed: "failed",
} as const;
export type AgentTrajectoryEventProcessingState =
    (typeof AgentTrajectoryEventProcessingState)[keyof typeof AgentTrajectoryEventProcessingState];
