// This file was auto-generated by Fern from our API Definition.

export interface AgentVerifierPrincipal {
    /** The exact principal identifier. Wildcards are not supported. */
    principalId: string;
    /** The authenticated principal type: member, project-api-key, service, or mcp_user. */
    principalType: string;
}
