// This file was auto-generated by Fern from our API Definition.

export interface AgentSkillEvidence {
    assertionUuid?: string;
    createdAt?: string;
    occurredAt?: string;
    polarity?: string;
    sourceKind?: string;
    summaryVersionUuid?: string;
    trajectoryEventUuid?: string;
    trajectoryUuid?: string;
    verification?: string;
}
