// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../index.js";

export interface AgentPage {
    /** The Agents on this page. */
    items?: Zep.Agent[];
    /**
     * Opaque cursor for retrieving the next page, present only when more results
     * are available.
     */
    nextCursor?: string;
    /** The total number of Agents matching the filters and authorization scope. */
    totalSize?: number;
}
