// This file was auto-generated by Fern from our API Definition.

export const AgentMemorySettingsApproval = {
    Manual: "manual",
    Auto: "auto",
} as const;
export type AgentMemorySettingsApproval =
    (typeof AgentMemorySettingsApproval)[keyof typeof AgentMemorySettingsApproval];
