// This file was auto-generated by Fern from our API Definition.

export interface ArtifactListRequest {
    /** Filters constraining which items are returned. */
    filters?: Record<string, unknown>;
}
