/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BatchStatus = "draft" | "invalid" | "queued" | "processing" | "succeeded" | "partial" | "failed";
export const BatchStatus = {
    Draft: "draft",
    Invalid: "invalid",
    Queued: "queued",
    Processing: "processing",
    Succeeded: "succeeded",
    Partial: "partial",
    Failed: "failed",
} as const;
