// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../index.js";

export interface ContentPolicyEvent {
    /**
     * The kind of artifact the decision applied to. episode marks the
     * episode-level record that carries every matched category.
     */
    artifactKind?: Zep.ContentPolicyEventArtifactKind;
    /** The keys of the categories with a matched rule. */
    categoryKeys?: string[];
    /** The time of the decision. */
    decidedAt?: string;
    /**
     * Why the artifact was dropped: match, indeterminate, oversize, or
     * dependent.
     */
    dropReason?: Zep.ContentPolicyEventDropReason;
    /** The episode the decision belongs to. */
    episodeUuid?: string;
    /** The opaque identifier of the event. */
    id?: string;
    /** The project revision number of the policy the graph bound. */
    revision?: number;
    /** The identifiers of the rules that matched. */
    ruleIds?: string[];
}
