// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../index.js";

export interface DateFilter {
    /** The temporal field to compare. */
    field?: Zep.DateFilterField;
    /** The lowercase comparison operator. */
    operator?: Zep.DateFilterOperator;
    /** The RFC 3339 timestamp. Omit this field for null operators. */
    value?: Date;
}
