/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Zep from "../index.js";

export interface Graph {
    created_at?: string;
    description?: string;
    fact_rating_instruction?: Zep.FactRatingInstruction;
    graph_id?: string;
    id?: number;
    name?: string;
    project_uuid?: string;
    uuid?: string;
}
