/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GraphSearchScope = "edges" | "nodes" | "episodes" | "communities" | "sagas" | "themes" | "auto";
export const GraphSearchScope = {
    Edges: "edges",
    Nodes: "nodes",
    Episodes: "episodes",
    Communities: "communities",
    Sagas: "sagas",
    Themes: "themes",
    Auto: "auto",
} as const;
