// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../index.js";

export interface IngestionTracePage {
    /** The ingestion traces on this page. */
    items?: Zep.IngestionTrace[];
    /**
     * The cursor to pass as the next request's cursor to fetch the following
     * page; absent when no further pages remain.
     */
    nextCursor?: string;
}
