/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Zep from "../index";

export interface Message {
    /** The content of the message. */
    content: string;
    /** The timestamp of when the message was created. */
    createdAt?: string;
    /** The metadata associated with the message. */
    metadata?: Record<string, unknown>;
    /** Customizable role of the sender of the message (e.g., "john", "sales_agent"). */
    role?: string;
    /** The type of the role (e.g., "user", "system"). */
    roleType: Zep.RoleType;
    /** Deprecated */
    tokenCount?: number;
    /** Deprecated */
    updatedAt?: string;
    /** The unique identifier of the message. */
    uuid?: string;
}
