// This file was auto-generated by Fern from our API Definition.

export interface ThreadSummary {
    /** The time the summary was first created. */
    createdAt?: string;
    /** The wall-clock time of the most recent summary update. */
    lastSummarizedAt?: string;
    /**
     * The latest episode reference time covered by the most recent summary
     * update.
     */
    lastSummarizedEpisodeValidAt?: string;
    /**
     * A cross-encoder-derived relevance score, present only when the
     * cross-encoder reranker scored this result; like score, it is omitted from
     * plain list results.
     */
    relevance?: number;
    /**
     * A score accompanies every search result; it is omitted when the summary
     * appears in a plain list rather than a search result.
     */
    score?: number;
    /** The generated summary text for the thread. */
    summary?: string;
    /** The unique identifier of the thread this summary belongs to. */
    threadUuid?: string;
    /** The unique identifier of the thread summary. */
    uuid?: string;
}
