/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Zep from "../index.js";

export interface UserGroupListResponse {
    quota?: Zep.UserGroupQuota;
    rowCount?: number;
    totalCount?: number;
    userGroups?: Zep.UserGroup[];
}
