// This file was auto-generated by Fern from our API Definition.

/** The role of the message's sender, for a thread_message item. */
export const V4BatchItemInputRole = {
    System: "system",
    Assistant: "assistant",
    User: "user",
    Function: "function",
    Tool: "tool",
} as const;
export type V4BatchItemInputRole = (typeof V4BatchItemInputRole)[keyof typeof V4BatchItemInputRole];
