// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const UserListRequest: core.serialization.Schema<
    serializers.UserListRequest.Raw,
    Omit<Zep.UserListRequest, "limit" | "cursor" | "orderBy" | "order">
> = core.serialization.object({
    search: core.serialization.string().optional(),
});

export declare namespace UserListRequest {
    export interface Raw {
        search?: string | null;
    }
}
