/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Zep from "../../../../index";

/**
 * @example
 *     {
 *         data: "data",
 *         type: "text"
 *     }
 */
export interface AddDataRequest {
    data: string;
    groupId?: string;
    sourceDescription?: string;
    type: Zep.GraphDataType;
    userId?: string;
}
