/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         graphId: "graph_id"
 *     }
 */
export interface CreateGraphRequest {
    description?: string;
    graphId: string;
    name?: string;
    /** The graph's IANA time zone. Stored on its group-backed subject. */
    timeZone?: string;
}
