/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Zep from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface EntityTypeRequest {
    edge_types?: Zep.EdgeType[];
    entity_types?: Zep.EntityType[];
}
