// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GraphContextRequest {
    filters?: Record<string, unknown>;
    includeResults?: boolean;
    maxCharacters?: number;
    query?: string;
    recencyBias?: string;
    templateUuid?: string;
}
