/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         userId: "user_id",
 *         graphId: "graph_id"
 *     }
 */
export interface GraphListEntityTypesRequest {
    /**
     * User ID to get user-specific entity types
     */
    userId?: string;
    /**
     * Graph ID to get graph-specific entity types
     */
    graphId?: string;
}
