/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         pageNumber: 1,
 *         pageSize: 1
 *     }
 */
export interface GraphListAllRequest {
    /**
     * Page number for pagination, starting from 1.
     */
    pageNumber?: number;
    /**
     * Number of graphs to retrieve per page.
     */
    pageSize?: number;
}
