// This file was auto-generated by Fern from our API Definition.

import * as Zep from "../../../src/api/index";
import { ZepClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("MessageClient", () => {
    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { metadata: { key: "value" } };
        const rawResponseBody = {
            content: "content",
            created_at: "created_at",
            metadata: { key: "value" },
            name: "name",
            processed: true,
            role: "norole",
            uuid: "uuid",
        };

        server
            .mockEndpoint()
            .patch("/messages/messageUUID")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.thread.message.update("messageUUID", {
            metadata: {
                key: "value",
            },
        });
        expect(response).toEqual({
            content: "content",
            createdAt: "created_at",
            metadata: {
                key: "value",
            },
            name: "name",
            processed: true,
            role: "norole",
            uuid: "uuid",
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { metadata: { metadata: { key: "value" } } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/messages/messageUUID")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.thread.message.update("messageUUID", {
                metadata: {
                    metadata: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Zep.NotFoundError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { metadata: { metadata: { key: "value" } } };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/messages/messageUUID")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.thread.message.update("messageUUID", {
                metadata: {
                    metadata: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Zep.InternalServerError);
    });
});
