// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentSkillSearchHitMaturity: core.serialization.Schema<
    serializers.AgentSkillSearchHitMaturity.Raw,
    Zep.AgentSkillSearchHitMaturity
> = core.serialization.enum_(["provisional", "corroborated", "established", "authored"]);

export declare namespace AgentSkillSearchHitMaturity {
    export type Raw = "provisional" | "corroborated" | "established" | "authored";
}
