// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentSkillSearchHit } from "./AgentSkillSearchHit.js";

export const AgentSkillSearchResponse: core.serialization.ObjectSchema<
    serializers.AgentSkillSearchResponse.Raw,
    Zep.AgentSkillSearchResponse
> = core.serialization.object({
    items: core.serialization.list(AgentSkillSearchHit).optional(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    searchId: core.serialization.property("search_id", core.serialization.string().optional()),
});

export declare namespace AgentSkillSearchResponse {
    export interface Raw {
        items?: AgentSkillSearchHit.Raw[] | null;
        next_cursor?: string | null;
        search_id?: string | null;
    }
}
