// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentBreakingChange: core.serialization.ObjectSchema<
    serializers.AgentBreakingChange.Raw,
    Zep.AgentBreakingChange
> = core.serialization.object({
    affectedSkillCount: core.serialization.property("affected_skill_count", core.serialization.number().optional()),
    agentUuid: core.serialization.property("agent_uuid", core.serialization.string().optional()),
    revision: core.serialization.number().optional(),
    uuid: core.serialization.string().optional(),
    version: core.serialization.string().optional(),
});

export declare namespace AgentBreakingChange {
    export interface Raw {
        affected_skill_count?: number | null;
        agent_uuid?: string | null;
        revision?: number | null;
        uuid?: string | null;
        version?: string | null;
    }
}
