// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentVerificationStrength } from "./AgentVerificationStrength.js";
import { AgentVerifierPrincipal } from "./AgentVerifierPrincipal.js";
import { AgentVerifierPrincipalBinding } from "./AgentVerifierPrincipalBinding.js";
import { AgentVerifierStatus } from "./AgentVerifierStatus.js";

export const AgentVerifier: core.serialization.ObjectSchema<serializers.AgentVerifier.Raw, Zep.AgentVerifier> =
    core.serialization.object({
        agentUuid: core.serialization.property("agent_uuid", core.serialization.string().optional()),
        capabilities: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        class: core.serialization.string().optional(),
        createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
        createdBy: core.serialization.property("created_by", AgentVerifierPrincipal.optional()),
        metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        permittedStrengths: core.serialization.property(
            "permitted_strengths",
            core.serialization.list(AgentVerificationStrength).optional(),
        ),
        principalBindings: core.serialization.property(
            "principal_bindings",
            core.serialization.list(AgentVerifierPrincipalBinding).optional(),
        ),
        revision: core.serialization.number().optional(),
        revokedAt: core.serialization.property("revoked_at", core.serialization.string().optional()),
        status: AgentVerifierStatus.optional(),
        updatedAt: core.serialization.property("updated_at", core.serialization.string().optional()),
        uuid: core.serialization.string().optional(),
        verifierId: core.serialization.property("verifier_id", core.serialization.string().optional()),
    });

export declare namespace AgentVerifier {
    export interface Raw {
        agent_uuid?: string | null;
        capabilities?: Record<string, unknown> | null;
        class?: string | null;
        created_at?: string | null;
        created_by?: AgentVerifierPrincipal.Raw | null;
        metadata?: Record<string, unknown> | null;
        permitted_strengths?: AgentVerificationStrength.Raw[] | null;
        principal_bindings?: AgentVerifierPrincipalBinding.Raw[] | null;
        revision?: number | null;
        revoked_at?: string | null;
        status?: AgentVerifierStatus.Raw | null;
        updated_at?: string | null;
        uuid?: string | null;
        verifier_id?: string | null;
    }
}
