// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentVerificationStrength: core.serialization.Schema<
    serializers.AgentVerificationStrength.Raw,
    Zep.AgentVerificationStrength
> = core.serialization.enum_(["tool_verified", "customer_verified", "externally_verified"]);

export declare namespace AgentVerificationStrength {
    export type Raw = "tool_verified" | "customer_verified" | "externally_verified";
}
