// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentSkillCandidateReviewSummary: core.serialization.ObjectSchema<
    serializers.AgentSkillCandidateReviewSummary.Raw,
    Zep.AgentSkillCandidateReviewSummary
> = core.serialization.object({
    candidateCount: core.serialization.property("candidate_count", core.serialization.number().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    reasonCode: core.serialization.property("reason_code", core.serialization.string().optional()),
    reviewedAt: core.serialization.property("reviewed_at", core.serialization.string().optional()),
    revision: core.serialization.number().optional(),
    status: core.serialization.string().optional(),
    taskFamily: core.serialization.property("task_family", core.serialization.string().optional()),
    uuid: core.serialization.string().optional(),
});

export declare namespace AgentSkillCandidateReviewSummary {
    export interface Raw {
        candidate_count?: number | null;
        created_at?: string | null;
        reason_code?: string | null;
        reviewed_at?: string | null;
        revision?: number | null;
        status?: string | null;
        task_family?: string | null;
        uuid?: string | null;
    }
}
