// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentStatus: core.serialization.Schema<serializers.AgentStatus.Raw, Zep.AgentStatus> =
    core.serialization.enum_(["active", "deleting", "deletion_failed"]);

export declare namespace AgentStatus {
    export type Raw = "active" | "deleting" | "deletion_failed";
}
