// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Batch: core.serialization.ObjectSchema<serializers.Batch.Raw, Zep.Batch> = core.serialization.object({
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    progress: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    status: core.serialization.string().optional(),
    strictOntology: core.serialization.property("strict_ontology", core.serialization.boolean().optional()),
    uuid: core.serialization.string().optional(),
});

export declare namespace Batch {
    export interface Raw {
        created_at?: string | null;
        metadata?: Record<string, unknown> | null;
        progress?: Record<string, unknown> | null;
        status?: string | null;
        strict_ontology?: boolean | null;
        uuid?: string | null;
    }
}
