/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";

export const CloneGraphResponse: core.serialization.ObjectSchema<
    serializers.CloneGraphResponse.Raw,
    Zep.CloneGraphResponse
> = core.serialization.object({
    graphId: core.serialization.property("graph_id", core.serialization.string().optional()),
    taskId: core.serialization.property("task_id", core.serialization.string().optional()),
    userId: core.serialization.property("user_id", core.serialization.string().optional()),
});

export declare namespace CloneGraphResponse {
    export interface Raw {
        graph_id?: string | null;
        task_id?: string | null;
        user_id?: string | null;
    }
}
