// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ContextThreadSummary: core.serialization.ObjectSchema<
    serializers.ContextThreadSummary.Raw,
    Zep.ContextThreadSummary
> = core.serialization.object({
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    lastSummarizedAt: core.serialization.property("last_summarized_at", core.serialization.string().optional()),
    lastSummarizedEpisodeValidAt: core.serialization.property(
        "last_summarized_episode_valid_at",
        core.serialization.string().optional(),
    ),
    relevance: core.serialization.number().optional(),
    score: core.serialization.number().optional(),
    selectionRank: core.serialization.property("selection_rank", core.serialization.number().optional()),
    summary: core.serialization.string().optional(),
    threadUuid: core.serialization.property("thread_uuid", core.serialization.string().optional()),
    uuid: core.serialization.string().optional(),
});

export declare namespace ContextThreadSummary {
    export interface Raw {
        created_at?: string | null;
        last_summarized_at?: string | null;
        last_summarized_episode_valid_at?: string | null;
        relevance?: number | null;
        score?: number | null;
        selection_rank?: number | null;
        summary?: string | null;
        thread_uuid?: string | null;
        uuid?: string | null;
    }
}
