// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ContentPolicyRuleRequest: core.serialization.ObjectSchema<
    serializers.ContentPolicyRuleRequest.Raw,
    Zep.ContentPolicyRuleRequest
> = core.serialization.object({
    categoryKey: core.serialization.property("category_key", core.serialization.string().optional()),
    description: core.serialization.string().optional(),
    permittedExamples: core.serialization.property(
        "permitted_examples",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    prohibitedExamples: core.serialization.property(
        "prohibited_examples",
        core.serialization.list(core.serialization.string()).optional(),
    ),
});

export declare namespace ContentPolicyRuleRequest {
    export interface Raw {
        category_key?: string | null;
        description?: string | null;
        permitted_examples?: string[] | null;
        prohibited_examples?: string[] | null;
    }
}
