// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CreateContextTemplateRequest: core.serialization.ObjectSchema<
    serializers.CreateContextTemplateRequest.Raw,
    Zep.CreateContextTemplateRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    template: core.serialization.string().optional(),
});

export declare namespace CreateContextTemplateRequest {
    export interface Raw {
        name?: string | null;
        template?: string | null;
    }
}
