// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Edge } from "./Edge.js";

export const EdgePage: core.serialization.ObjectSchema<serializers.EdgePage.Raw, Zep.EdgePage> =
    core.serialization.object({
        items: core.serialization.list(Edge).optional(),
        nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
        totalSize: core.serialization.property("total_size", core.serialization.number().optional()),
    });

export declare namespace EdgePage {
    export interface Raw {
        items?: Edge.Raw[] | null;
        next_cursor?: string | null;
        total_size?: number | null;
    }
}
