/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Zep from "../../api/index";
import * as core from "../../core";

export const EntityNode: core.serialization.ObjectSchema<serializers.EntityNode.Raw, Zep.EntityNode> =
    core.serialization.object({
        createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
        labels: core.serialization.list(core.serialization.string()).optional(),
        name: core.serialization.string().optional(),
        summary: core.serialization.string().optional(),
        uuid: core.serialization.string().optional(),
    });

export declare namespace EntityNode {
    interface Raw {
        created_at?: string | null;
        labels?: string[] | null;
        name?: string | null;
        summary?: string | null;
        uuid?: string | null;
    }
}
