/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import { RoleType } from "./RoleType.js";
import { GraphDataType } from "./GraphDataType.js";

export const Episode: core.serialization.ObjectSchema<serializers.Episode.Raw, Zep.Episode> = core.serialization.object(
    {
        content: core.serialization.string(),
        createdAt: core.serialization.property("created_at", core.serialization.string()),
        metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        processed: core.serialization.boolean().optional(),
        relevance: core.serialization.number().optional(),
        role: core.serialization.string().optional(),
        roleType: core.serialization.property("role_type", RoleType.optional()),
        score: core.serialization.number().optional(),
        source: GraphDataType.optional(),
        sourceDescription: core.serialization.property("source_description", core.serialization.string().optional()),
        taskId: core.serialization.property("task_id", core.serialization.string().optional()),
        threadId: core.serialization.property("thread_id", core.serialization.string().optional()),
        uuid: core.serialization.string(),
    },
);

export declare namespace Episode {
    export interface Raw {
        content: string;
        created_at: string;
        metadata?: Record<string, unknown> | null;
        processed?: boolean | null;
        relevance?: number | null;
        role?: string | null;
        role_type?: RoleType.Raw | null;
        score?: number | null;
        source?: GraphDataType.Raw | null;
        source_description?: string | null;
        task_id?: string | null;
        thread_id?: string | null;
        uuid: string;
    }
}
