/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";

export const GraphEpisodeListRequest: core.serialization.ObjectSchema<
    serializers.GraphEpisodeListRequest.Raw,
    Zep.GraphEpisodeListRequest
> = core.serialization.object({
    cursor: core.serialization.string().optional(),
    direction: core.serialization.string().optional(),
    limit: core.serialization.number().optional(),
    mentionedNodeUuids: core.serialization.property(
        "mentioned_node_uuids",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    orderBy: core.serialization.property("order_by", core.serialization.string().optional()),
});

export declare namespace GraphEpisodeListRequest {
    export interface Raw {
        cursor?: string | null;
        direction?: string | null;
        limit?: number | null;
        mentioned_node_uuids?: string[] | null;
        order_by?: string | null;
    }
}
