// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Graph: core.serialization.ObjectSchema<serializers.Graph.Raw, Zep.Graph> = core.serialization.object({
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    description: core.serialization.string().optional(),
    graphId: core.serialization.property("graph_id", core.serialization.string().optional()),
    name: core.serialization.string().optional(),
    timeZone: core.serialization.property("time_zone", core.serialization.string().optional()),
    type: core.serialization.string().optional(),
    updatedAt: core.serialization.property("updated_at", core.serialization.string().optional()),
    userUuid: core.serialization.property("user_uuid", core.serialization.string().optional()),
    uuid: core.serialization.string().optional(),
});

export declare namespace Graph {
    export interface Raw {
        created_at?: string | null;
        description?: string | null;
        graph_id?: string | null;
        name?: string | null;
        time_zone?: string | null;
        type?: string | null;
        updated_at?: string | null;
        user_uuid?: string | null;
        uuid?: string | null;
    }
}
