/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";

export const GraphThreadSummariesRequest: core.serialization.ObjectSchema<
    serializers.GraphThreadSummariesRequest.Raw,
    Zep.GraphThreadSummariesRequest
> = core.serialization.object({
    limit: core.serialization.number().optional(),
    uuidCursor: core.serialization.property("uuid_cursor", core.serialization.string().optional()),
});

export declare namespace GraphThreadSummariesRequest {
    export interface Raw {
        limit?: number | null;
        uuid_cursor?: string | null;
    }
}
