// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { IngestionTraceEdgeReference } from "./IngestionTraceEdgeReference.js";

export const IngestionTraceEdgeInvalidation: core.serialization.ObjectSchema<
    serializers.IngestionTraceEdgeInvalidation.Raw,
    Zep.IngestionTraceEdgeInvalidation
> = core.serialization.object({
    invalidatedEdgeUuid: core.serialization.property("invalidated_edge_uuid", core.serialization.string().optional()),
    invalidatingEdges: core.serialization.property(
        "invalidating_edges",
        core.serialization.list(IngestionTraceEdgeReference).optional(),
    ),
});

export declare namespace IngestionTraceEdgeInvalidation {
    export interface Raw {
        invalidated_edge_uuid?: string | null;
        invalidating_edges?: IngestionTraceEdgeReference.Raw[] | null;
    }
}
