/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Zep from "../../api/index";
import * as core from "../../core";
import { RoleType } from "./RoleType";

export const Message: core.serialization.ObjectSchema<serializers.Message.Raw, Zep.Message> = core.serialization.object(
    {
        uuid: core.serialization.string().optional(),
        createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
        role: core.serialization.string().optional(),
        roleType: core.serialization.property("role_type", RoleType),
        content: core.serialization.string(),
        metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        updatedAt: core.serialization.property("updated_at", core.serialization.string().optional()),
        tokenCount: core.serialization.property("token_count", core.serialization.number().optional()),
    },
);

export declare namespace Message {
    export interface Raw {
        uuid?: string | null;
        created_at?: string | null;
        role?: string | null;
        role_type: RoleType.Raw;
        content: string;
        metadata?: Record<string, unknown> | null;
        updated_at?: string | null;
        token_count?: number | null;
    }
}
