/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Zep from "../../api";
import * as core from "../../core";

export const ModelsClassifySessionResponse: core.serialization.ObjectSchema<
    serializers.ModelsClassifySessionResponse.Raw,
    Zep.ModelsClassifySessionResponse
> = core.serialization.object({
    class: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
});

export declare namespace ModelsClassifySessionResponse {
    interface Raw {
        class?: string | null;
        name?: string | null;
    }
}
