// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Node } from "./Node.js";

export const NodePage: core.serialization.ObjectSchema<serializers.NodePage.Raw, Zep.NodePage> =
    core.serialization.object({
        items: core.serialization.list(Node).optional(),
        nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
        totalSize: core.serialization.property("total_size", core.serialization.number().optional()),
    });

export declare namespace NodePage {
    export interface Raw {
        items?: Node.Raw[] | null;
        next_cursor?: string | null;
        total_size?: number | null;
    }
}
