// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentSkillEvidence } from "./AgentSkillEvidence.js";

export const Pagev4AgentSkillEvidence: core.serialization.ObjectSchema<
    serializers.Pagev4AgentSkillEvidence.Raw,
    Zep.Pagev4AgentSkillEvidence
> = core.serialization.object({
    items: core.serialization.list(AgentSkillEvidence).optional(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    totalSize: core.serialization.property("total_size", core.serialization.number().optional()),
});

export declare namespace Pagev4AgentSkillEvidence {
    export interface Raw {
        items?: AgentSkillEvidence.Raw[] | null;
        next_cursor?: string | null;
        total_size?: number | null;
    }
}
