// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PathDetectConfig: core.serialization.ObjectSchema<serializers.PathDetectConfig.Raw, Zep.PathDetectConfig> =
    core.serialization.object({
        maxHops: core.serialization.property("max_hops", core.serialization.number().optional()),
    });

export declare namespace PathDetectConfig {
    export interface Raw {
        max_hops?: number | null;
    }
}
