/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Zep from "../../api/index";
import * as core from "../../core";

export const SearchType: core.serialization.Schema<serializers.SearchType.Raw, Zep.SearchType> =
    core.serialization.enum_(["similarity", "mmr"]);

export declare namespace SearchType {
    export type Raw = "similarity" | "mmr";
}
