/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Zep from "../../api/index";
import * as core from "../../core";
import { Session } from "./Session";

export const SessionListResponse: core.serialization.ObjectSchema<
    serializers.SessionListResponse.Raw,
    Zep.SessionListResponse
> = core.serialization.object({
    responseCount: core.serialization.property("response_count", core.serialization.number().optional()),
    sessions: core.serialization.list(Session).optional(),
    totalCount: core.serialization.property("total_count", core.serialization.number().optional()),
});

export declare namespace SessionListResponse {
    interface Raw {
        response_count?: number | null;
        sessions?: Session.Raw[] | null;
        total_count?: number | null;
    }
}
