// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SkillResource: core.serialization.ObjectSchema<serializers.SkillResource.Raw, Zep.SkillResource> =
    core.serialization.object({
        aliases: core.serialization.list(core.serialization.string()).optional(),
        name: core.serialization.string().optional(),
        version: core.serialization.string().optional(),
    });

export declare namespace SkillResource {
    export interface Raw {
        aliases?: string[] | null;
        name?: string | null;
        version?: string | null;
    }
}
