// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SkillDefinitionSection: core.serialization.ObjectSchema<
    serializers.SkillDefinitionSection.Raw,
    Zep.SkillDefinitionSection
> = core.serialization.object({
    heading: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
    markdown: core.serialization.string().optional(),
});

export declare namespace SkillDefinitionSection {
    export interface Raw {
        heading?: string | null;
        id?: string | null;
        markdown?: string | null;
    }
}
