// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TaskFamilyMappingRuleSource: core.serialization.Schema<
    serializers.TaskFamilyMappingRuleSource.Raw,
    Zep.TaskFamilyMappingRuleSource
> = core.serialization.enum_(["fixed", "metadata", "tag_prefix", "name"]);

export declare namespace TaskFamilyMappingRuleSource {
    export type Raw = "fixed" | "metadata" | "tag_prefix" | "name";
}
