// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ThreadSummary } from "./ThreadSummary.js";

export const ThreadSummaryPage: core.serialization.ObjectSchema<
    serializers.ThreadSummaryPage.Raw,
    Zep.ThreadSummaryPage
> = core.serialization.object({
    items: core.serialization.list(ThreadSummary).optional(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    totalSize: core.serialization.property("total_size", core.serialization.number().optional()),
});

export declare namespace ThreadSummaryPage {
    export interface Raw {
        items?: ThreadSummary.Raw[] | null;
        next_cursor?: string | null;
        total_size?: number | null;
    }
}
