// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TraceProviderProject: core.serialization.ObjectSchema<
    serializers.TraceProviderProject.Raw,
    Zep.TraceProviderProject
> = core.serialization.object({
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
});

export declare namespace TraceProviderProject {
    export interface Raw {
        created_at?: string | null;
        id?: string | null;
        name?: string | null;
    }
}
