// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TraceConnectionSettings: core.serialization.ObjectSchema<
    serializers.TraceConnectionSettings.Raw,
    Zep.TraceConnectionSettings
> = core.serialization.object({
    apiUrl: core.serialization.property("api_url", core.serialization.string().optional()),
    requestsPerMinute: core.serialization.property("requests_per_minute", core.serialization.number().optional()),
    retentionDays: core.serialization.property("retention_days", core.serialization.number().optional()),
});

export declare namespace TraceConnectionSettings {
    export interface Raw {
        api_url?: string | null;
        requests_per_minute?: number | null;
        retention_days?: number | null;
    }
}
