// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TraceConnection } from "./TraceConnection.js";

export const TraceConnectionPage: core.serialization.ObjectSchema<
    serializers.TraceConnectionPage.Raw,
    Zep.TraceConnectionPage
> = core.serialization.object({
    items: core.serialization.list(TraceConnection).optional(),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    totalSize: core.serialization.property("total_size", core.serialization.number().optional()),
});

export declare namespace TraceConnectionPage {
    export interface Raw {
        items?: TraceConnection.Raw[] | null;
        next_cursor?: string | null;
        total_size?: number | null;
    }
}
