/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Zep from "../../api/index";
import * as core from "../../core";
import { EntityNode } from "./EntityNode";

export const UserNodeResponse: core.serialization.ObjectSchema<serializers.UserNodeResponse.Raw, Zep.UserNodeResponse> =
    core.serialization.object({
        node: EntityNode.optional(),
    });

export declare namespace UserNodeResponse {
    export interface Raw {
        node?: EntityNode.Raw | null;
    }
}
