/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 *
 * @example
 *     {}
 *
 * @example
 *     {}
 *
 * @example
 *     {}
 *
 * @example
 *     {}
 *
 * @example
 *     {}
 */
export interface CreateDocumentCollectionRequest {
    description?: string;
    metadata?: Record<string, unknown>;
}
