// This file was auto-generated by Fern from our API Definition.

import type {
    BaseClientOptions,
    BaseIdempotentRequestOptions,
    BaseRequestOptions,
} from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import { generateIdempotencyKey, getIdempotencyHeaders } from "../../../../../../core/idempotency.js";
import * as core from "../../../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../../../core/requestBody.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as serializers from "../../../../../../serialization/index.js";
import * as Zep from "../../../../../index.js";

export declare namespace EpisodeClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}

    export interface IdempotentRequestOptions extends RequestOptions, BaseIdempotentRequestOptions {}
}

export class EpisodeClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EpisodeClient.Options>;

    constructor(options: EpisodeClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {string} graph_uuid - Graph UUID
     * @param {string} document_id - Document ID
     * @param {Zep.graph.EpisodeListForDocumentRequest} request
     * @param {EpisodeClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zep.BadRequestError}
     * @throws {@link Zep.UnauthorizedError}
     * @throws {@link Zep.ForbiddenError}
     * @throws {@link Zep.NotFoundError}
     * @throws {@link Zep.ConflictError}
     * @throws {@link errors.ZepError}
     * @throws {@link errors.ZepTimeoutError}
     *
     * @example
     *     await client.graph.episode.listForDocument("graph_uuid", "document_id")
     */
    public async listForDocument(
        graph_uuid: string,
        document_id: string,
        request: Zep.graph.EpisodeListForDocumentRequest = {},
        requestOptions?: EpisodeClient.RequestOptions,
    ): Promise<core.Page<Zep.Episode, Zep.EpisodePage>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Zep.graph.EpisodeListForDocumentRequest,
            ): Promise<core.WithRawResponse<Zep.EpisodePage>> => {
                const { limit, cursor } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    cursor,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.ZepEnvironment.Default,
                        `graphs/${core.url.encodePathParam(graph_uuid)}/documents/${core.url.encodePathParam(document_id)}/episodes`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: serializers.EpisodePage.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Zep.BadRequestError(
                                serializers.ApiError.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Zep.UnauthorizedError(
                                serializers.ApiError.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Zep.ForbiddenError(
                                serializers.ApiError.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 404:
                            throw new Zep.NotFoundError(
                                serializers.ApiError.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 409:
                            throw new Zep.ConflictError(
                                serializers.ApiError.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.ZepError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/graphs/{graph_uuid}/documents/{document_id}/episodes",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Zep.Episode, Zep.EpisodePage>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.nextCursor != null &&
                !(typeof response?.nextCursor === "string" && response?.nextCursor === ""),
            getItems: (response) => response?.items ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.nextCursor));
            },
        });
    }

    /**
     * @param {string} graph_uuid - Graph UUID
     * @param {Zep.graph.AddEpisodeRequest} request
     * @param {EpisodeClient.IdempotentRequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zep.BadRequestError}
     * @throws {@link Zep.UnauthorizedError}
     * @throws {@link Zep.ForbiddenError}
     * @throws {@link Zep.NotFoundError}
     * @throws {@link Zep.ConflictError}
     * @throws {@link errors.ZepError}
     * @throws {@link errors.ZepTimeoutError}
     *
     * @example
     *     await client.graph.episode.add("graph_uuid", {
     *         data: "data"
     *     })
     */
    public add(
        graph_uuid: string,
        request: Zep.graph.AddEpisodeRequest,
        requestOptions?: EpisodeClient.IdempotentRequestOptions,
    ): core.HttpResponsePromise<Zep.AddEpisodeResult> {
        return core.HttpResponsePromise.fromPromise(this.__add(graph_uuid, request, requestOptions));
    }

    private async __add(
        graph_uuid: string,
        request: Zep.graph.AddEpisodeRequest,
        requestOptions?: EpisodeClient.IdempotentRequestOptions,
    ): Promise<core.WithRawResponse<Zep.AddEpisodeResult>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Idempotency-Key": requestOptions?.idempotencyKey ?? generateIdempotencyKey() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZepEnvironment.Default,
                `graphs/${core.url.encodePathParam(graph_uuid)}/episodes`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(
                serializers.graph.AddEpisodeRequest.jsonOrThrow(request, {
                    unrecognizedObjectKeys: "strip",
                    omitUndefined: true,
                }),
                requestOptions?.additionalBodyParameters,
            ),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.AddEpisodeResult.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Zep.BadRequestError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 401:
                    throw new Zep.UnauthorizedError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new Zep.ForbiddenError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new Zep.NotFoundError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 409:
                    throw new Zep.ConflictError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ZepError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/graphs/{graph_uuid}/episodes",
        );
    }

    /**
     * Lists the episodes of a graph. `filters.mentioned_node_uuids` restricts
     * the results to episodes that mention any of the listed node UUIDs. The
     * list can also contain episode UUIDs: an episode UUID matches that episode,
     * so one request can return a known set of episodes. At most 256 entries.
     * `filters.metadata_filters` restricts the results to episodes whose stored
     * metadata matches the predicate.
     *
     * @param {string} graph_uuid - Graph UUID
     * @param {Zep.graph.EpisodeListRequest} request
     * @param {EpisodeClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zep.BadRequestError}
     * @throws {@link Zep.UnauthorizedError}
     * @throws {@link Zep.ForbiddenError}
     * @throws {@link Zep.NotFoundError}
     * @throws {@link errors.ZepError}
     * @throws {@link errors.ZepTimeoutError}
     *
     * @example
     *     await client.graph.episode.list("graph_uuid", {
     *         body: {}
     *     })
     */
    public async list(
        graph_uuid: string,
        request: Zep.graph.EpisodeListRequest,
        requestOptions?: EpisodeClient.RequestOptions,
    ): Promise<core.Page<Zep.Episode, Zep.EpisodePage>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (request: Zep.graph.EpisodeListRequest): Promise<core.WithRawResponse<Zep.EpisodePage>> => {
                const { limit, cursor, orderBy, order, body: _body } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    cursor,
                    order_by:
                        orderBy != null
                            ? serializers.graph.EpisodeListRequestOrderBy.jsonOrThrow(orderBy, {
                                  unrecognizedObjectKeys: "strip",
                                  omitUndefined: true,
                              })
                            : undefined,
                    order:
                        order != null
                            ? serializers.graph.EpisodeListRequestOrder.jsonOrThrow(order, {
                                  unrecognizedObjectKeys: "strip",
                                  omitUndefined: true,
                              })
                            : undefined,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    getIdempotencyHeaders(),
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.ZepEnvironment.Default,
                        `graphs/${core.url.encodePathParam(graph_uuid)}/episodes/list`,
                    ),
                    method: "POST",
                    headers: _headers,
                    contentType: "application/json",
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    requestType: "json",
                    body: mergeAdditionalBodyParameters(
                        serializers.ArtifactListRequest.jsonOrThrow(_body, {
                            unrecognizedObjectKeys: "strip",
                            omitUndefined: true,
                        }),
                        requestOptions?.additionalBodyParameters,
                    ),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: serializers.EpisodePage.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Zep.BadRequestError(
                                serializers.ApiError.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Zep.UnauthorizedError(
                                serializers.ApiError.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Zep.ForbiddenError(
                                serializers.ApiError.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 404:
                            throw new Zep.NotFoundError(
                                serializers.ApiError.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.ZepError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "POST",
                    "/graphs/{graph_uuid}/episodes/list",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Zep.Episode, Zep.EpisodePage>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.nextCursor != null &&
                !(typeof response?.nextCursor === "string" && response?.nextCursor === ""),
            getItems: (response) => response?.items ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.nextCursor));
            },
        });
    }

    /**
     * @param {string} graph_uuid - Graph UUID
     * @param {string} episode_uuid - Episode UUID
     * @param {EpisodeClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zep.BadRequestError}
     * @throws {@link Zep.UnauthorizedError}
     * @throws {@link Zep.ForbiddenError}
     * @throws {@link Zep.NotFoundError}
     * @throws {@link errors.ZepError}
     * @throws {@link errors.ZepTimeoutError}
     *
     * @example
     *     await client.graph.episode.get("graph_uuid", "episode_uuid")
     */
    public get(
        graph_uuid: string,
        episode_uuid: string,
        requestOptions?: EpisodeClient.RequestOptions,
    ): core.HttpResponsePromise<Zep.Episode> {
        return core.HttpResponsePromise.fromPromise(this.__get(graph_uuid, episode_uuid, requestOptions));
    }

    private async __get(
        graph_uuid: string,
        episode_uuid: string,
        requestOptions?: EpisodeClient.RequestOptions,
    ): Promise<core.WithRawResponse<Zep.Episode>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZepEnvironment.Default,
                `graphs/${core.url.encodePathParam(graph_uuid)}/episodes/${core.url.encodePathParam(episode_uuid)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.Episode.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Zep.BadRequestError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 401:
                    throw new Zep.UnauthorizedError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new Zep.ForbiddenError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new Zep.NotFoundError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ZepError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/graphs/{graph_uuid}/episodes/{episode_uuid}",
        );
    }

    /**
     * @param {string} graph_uuid - Graph UUID
     * @param {string} episode_uuid - Episode UUID
     * @param {EpisodeClient.IdempotentRequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zep.BadRequestError}
     * @throws {@link Zep.UnauthorizedError}
     * @throws {@link Zep.ForbiddenError}
     * @throws {@link Zep.NotFoundError}
     * @throws {@link Zep.ConflictError}
     * @throws {@link errors.ZepError}
     * @throws {@link errors.ZepTimeoutError}
     *
     * @example
     *     await client.graph.episode.delete("graph_uuid", "episode_uuid")
     */
    public delete(
        graph_uuid: string,
        episode_uuid: string,
        requestOptions?: EpisodeClient.IdempotentRequestOptions,
    ): core.HttpResponsePromise<Zep.AsyncResult> {
        return core.HttpResponsePromise.fromPromise(this.__delete(graph_uuid, episode_uuid, requestOptions));
    }

    private async __delete(
        graph_uuid: string,
        episode_uuid: string,
        requestOptions?: EpisodeClient.IdempotentRequestOptions,
    ): Promise<core.WithRawResponse<Zep.AsyncResult>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Idempotency-Key": requestOptions?.idempotencyKey ?? generateIdempotencyKey() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZepEnvironment.Default,
                `graphs/${core.url.encodePathParam(graph_uuid)}/episodes/${core.url.encodePathParam(episode_uuid)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.AsyncResult.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Zep.BadRequestError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 401:
                    throw new Zep.UnauthorizedError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new Zep.ForbiddenError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new Zep.NotFoundError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 409:
                    throw new Zep.ConflictError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ZepError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/graphs/{graph_uuid}/episodes/{episode_uuid}",
        );
    }

    /**
     * @param {string} graph_uuid - Graph UUID
     * @param {string} episode_uuid - Episode UUID
     * @param {Zep.graph.PatchEpisodeRequest} request
     * @param {EpisodeClient.IdempotentRequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zep.BadRequestError}
     * @throws {@link Zep.UnauthorizedError}
     * @throws {@link Zep.ForbiddenError}
     * @throws {@link Zep.NotFoundError}
     * @throws {@link Zep.ConflictError}
     * @throws {@link errors.ZepError}
     * @throws {@link errors.ZepTimeoutError}
     *
     * @example
     *     await client.graph.episode.update("graph_uuid", "episode_uuid")
     */
    public update(
        graph_uuid: string,
        episode_uuid: string,
        request: Zep.graph.PatchEpisodeRequest = {},
        requestOptions?: EpisodeClient.IdempotentRequestOptions,
    ): core.HttpResponsePromise<Zep.Episode> {
        return core.HttpResponsePromise.fromPromise(this.__update(graph_uuid, episode_uuid, request, requestOptions));
    }

    private async __update(
        graph_uuid: string,
        episode_uuid: string,
        request: Zep.graph.PatchEpisodeRequest = {},
        requestOptions?: EpisodeClient.IdempotentRequestOptions,
    ): Promise<core.WithRawResponse<Zep.Episode>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Idempotency-Key": requestOptions?.idempotencyKey ?? generateIdempotencyKey() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZepEnvironment.Default,
                `graphs/${core.url.encodePathParam(graph_uuid)}/episodes/${core.url.encodePathParam(episode_uuid)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(
                serializers.graph.PatchEpisodeRequest.jsonOrThrow(request, {
                    unrecognizedObjectKeys: "strip",
                    omitUndefined: true,
                }),
                requestOptions?.additionalBodyParameters,
            ),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.Episode.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Zep.BadRequestError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 401:
                    throw new Zep.UnauthorizedError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new Zep.ForbiddenError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new Zep.NotFoundError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 409:
                    throw new Zep.ConflictError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ZepError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/graphs/{graph_uuid}/episodes/{episode_uuid}",
        );
    }

    /**
     * Returns the ingestion workflow log of an episode. The log exists only when debug logging was enabled for the project when the episode was ingested (see `debug_log.enable`). The log holds episode content, so an API key with an ABAC policy needs an explicit grant of this action; the `readonly` macro does not grant it.
     *
     * @param {string} graph_uuid - Graph UUID
     * @param {string} episode_uuid - Episode UUID
     * @param {EpisodeClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zep.BadRequestError}
     * @throws {@link Zep.UnauthorizedError}
     * @throws {@link Zep.ForbiddenError}
     * @throws {@link Zep.NotFoundError}
     * @throws {@link errors.ZepError}
     * @throws {@link errors.ZepTimeoutError}
     *
     * @example
     *     await client.graph.episode.getDebugLogs("graph_uuid", "episode_uuid")
     */
    public getDebugLogs(
        graph_uuid: string,
        episode_uuid: string,
        requestOptions?: EpisodeClient.RequestOptions,
    ): core.HttpResponsePromise<Zep.EpisodeDebugLog> {
        return core.HttpResponsePromise.fromPromise(this.__getDebugLogs(graph_uuid, episode_uuid, requestOptions));
    }

    private async __getDebugLogs(
        graph_uuid: string,
        episode_uuid: string,
        requestOptions?: EpisodeClient.RequestOptions,
    ): Promise<core.WithRawResponse<Zep.EpisodeDebugLog>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ZepEnvironment.Default,
                `graphs/${core.url.encodePathParam(graph_uuid)}/episodes/${core.url.encodePathParam(episode_uuid)}/debug-logs`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.EpisodeDebugLog.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Zep.BadRequestError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 401:
                    throw new Zep.UnauthorizedError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new Zep.ForbiddenError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new Zep.NotFoundError(
                        serializers.ApiError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ZepError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/graphs/{graph_uuid}/episodes/{episode_uuid}/debug-logs",
        );
    }

    /**
     * Returns the ingestion traces of an episode, oldest first. Each trace records the input and the output of one ingestion step, with an explanation on each output entry that has one. Traces exist only when ingestion tracing was enabled for the project when the episode was ingested (see `debug_log.enable`). An episode with no traces returns a page with an empty `items` array. Traces hold episode content, prompt input, and model output, so an API key with an ABAC policy needs an explicit grant of this action; the `readonly` macro does not grant it.
     *
     * @param {string} graph_uuid - Graph UUID
     * @param {string} episode_uuid - Episode UUID
     * @param {Zep.graph.EpisodeListIngestionTracesRequest} request
     * @param {EpisodeClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Zep.BadRequestError}
     * @throws {@link Zep.UnauthorizedError}
     * @throws {@link Zep.ForbiddenError}
     * @throws {@link Zep.NotFoundError}
     * @throws {@link errors.ZepError}
     * @throws {@link errors.ZepTimeoutError}
     *
     * @example
     *     await client.graph.episode.listIngestionTraces("graph_uuid", "episode_uuid")
     */
    public async listIngestionTraces(
        graph_uuid: string,
        episode_uuid: string,
        request: Zep.graph.EpisodeListIngestionTracesRequest = {},
        requestOptions?: EpisodeClient.RequestOptions,
    ): Promise<core.Page<Zep.IngestionTrace, Zep.IngestionTracePage>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Zep.graph.EpisodeListIngestionTracesRequest,
            ): Promise<core.WithRawResponse<Zep.IngestionTracePage>> => {
                const { limit, cursor } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    cursor,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.ZepEnvironment.Default,
                        `graphs/${core.url.encodePathParam(graph_uuid)}/episodes/${core.url.encodePathParam(episode_uuid)}/ingestion-traces`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: serializers.IngestionTracePage.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Zep.BadRequestError(
                                serializers.ApiError.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Zep.UnauthorizedError(
                                serializers.ApiError.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Zep.ForbiddenError(
                                serializers.ApiError.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 404:
                            throw new Zep.NotFoundError(
                                serializers.ApiError.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.ZepError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/graphs/{graph_uuid}/episodes/{episode_uuid}/ingestion-traces",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Zep.IngestionTrace, Zep.IngestionTracePage>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.nextCursor != null &&
                !(typeof response?.nextCursor === "string" && response?.nextCursor === ""),
            getItems: (response) => response?.items ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.nextCursor));
            },
        });
    }
}
