/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         projectId: "projectId",
 *         policySetUuid: "policy_set_uuid"
 *     }
 */
export interface AttachPolicySetRequest {
    /**
     * Project UUID
     */
    projectId: string;
    policySetUuid: string;
}
