// This file was auto-generated by Fern from our API Definition.

import * as Zep from "../../../src/api/index";
import { ZepClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("SkillClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            items: [
                {
                    agent_versions: ["agent_versions"],
                    description: "description",
                    environments: ["environments"],
                    kind: "kind",
                    markdown: "markdown",
                    maturity: "provisional",
                    name: "name",
                    package_name: "package_name",
                    self_contained: true,
                    skill_id: "skill_id",
                    source_attempt_families: 1,
                    task_family: "task_family",
                    tools: ["tools"],
                    trust: 0.61,
                    uuid: "uuid",
                    verified_applications: 6,
                    version: 1,
                },
            ],
            next_cursor: "next_cursor",
            total_size: 1,
        };

        server
            .mockEndpoint({ once: false })
            .post("/agents/agent_uuid/skills/list")
            .jsonBody(rawRequestBody, { ignoredFields: ["cursor"] })
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            items: [
                {
                    agentVersions: ["agent_versions"],
                    description: "description",
                    environments: ["environments"],
                    kind: "kind",
                    markdown: "markdown",
                    maturity: "provisional",
                    name: "name",
                    packageName: "package_name",
                    selfContained: true,
                    skillId: "skill_id",
                    sourceAttemptFamilies: 1,
                    taskFamily: "task_family",
                    tools: ["tools"],
                    trust: 0.61,
                    uuid: "uuid",
                    verifiedApplications: 6,
                    version: 1,
                },
            ],
            nextCursor: "next_cursor",
            totalSize: 1,
        };
        const page = await client.agent.skill.list("agent_uuid");

        expect(expected.items).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.items).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/agents/agent_uuid/skills/list")
            .jsonBody(rawRequestBody, { ignoredFields: ["cursor"] })
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.list("agent_uuid");
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/agents/agent_uuid/skills/list")
            .jsonBody(rawRequestBody, { ignoredFields: ["cursor"] })
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.list("agent_uuid");
        }).rejects.toThrow(Zep.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/agents/agent_uuid/skills/list")
            .jsonBody(rawRequestBody, { ignoredFields: ["cursor"] })
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.list("agent_uuid");
        }).rejects.toThrow(Zep.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/agents/agent_uuid/skills/list")
            .jsonBody(rawRequestBody, { ignoredFields: ["cursor"] })
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.list("agent_uuid");
        }).rejects.toThrow(Zep.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/agents/agent_uuid/skills/list")
            .jsonBody(rawRequestBody, { ignoredFields: ["cursor"] })
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.list("agent_uuid");
        }).rejects.toThrow(Zep.ServiceUnavailableError);
    });

    test("search (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            items: [
                {
                    agent_versions: ["agent_versions"],
                    description: "description",
                    environments: ["environments"],
                    kind: "kind",
                    markdown: "markdown",
                    maturity: "provisional",
                    name: "name",
                    package_name: "package_name",
                    self_contained: true,
                    skill_id: "skill_id",
                    source_attempt_families: 1,
                    task_family: "task_family",
                    tools: ["tools"],
                    trust: 0.61,
                    uuid: "uuid",
                    verified_applications: 6,
                    version: 1,
                },
            ],
            next_cursor: "next_cursor",
            search_id: "search_id",
        };

        server
            .mockEndpoint({ once: false })
            .post("/agents/agent_uuid/skills/search")
            .jsonBody(rawRequestBody, { ignoredFields: ["cursor"] })
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            items: [
                {
                    agentVersions: ["agent_versions"],
                    description: "description",
                    environments: ["environments"],
                    kind: "kind",
                    markdown: "markdown",
                    maturity: "provisional",
                    name: "name",
                    packageName: "package_name",
                    selfContained: true,
                    skillId: "skill_id",
                    sourceAttemptFamilies: 1,
                    taskFamily: "task_family",
                    tools: ["tools"],
                    trust: 0.61,
                    uuid: "uuid",
                    verifiedApplications: 6,
                    version: 1,
                },
            ],
            nextCursor: "next_cursor",
            searchId: "search_id",
        };
        const page = await client.agent.skill.search("agent_uuid", {
            query: "query",
        });

        expect(expected.items).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.items).toEqual(nextPage.data);
    });

    test("search (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/agents/agent_uuid/skills/search")
            .jsonBody(rawRequestBody, { ignoredFields: ["cursor"] })
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.search("agent_uuid", {
                query: "query",
            });
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("search (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/agents/agent_uuid/skills/search")
            .jsonBody(rawRequestBody, { ignoredFields: ["cursor"] })
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.search("agent_uuid", {
                query: "query",
            });
        }).rejects.toThrow(Zep.UnauthorizedError);
    });

    test("search (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/agents/agent_uuid/skills/search")
            .jsonBody(rawRequestBody, { ignoredFields: ["cursor"] })
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.search("agent_uuid", {
                query: "query",
            });
        }).rejects.toThrow(Zep.ForbiddenError);
    });

    test("search (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/agents/agent_uuid/skills/search")
            .jsonBody(rawRequestBody, { ignoredFields: ["cursor"] })
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.search("agent_uuid", {
                query: "query",
            });
        }).rejects.toThrow(Zep.NotFoundError);
    });

    test("search (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/agents/agent_uuid/skills/search")
            .jsonBody(rawRequestBody, { ignoredFields: ["cursor"] })
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.search("agent_uuid", {
                query: "query",
            });
        }).rejects.toThrow(Zep.ServiceUnavailableError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            agent_versions: ["agent_versions"],
            created_at: "created_at",
            current_version: 1,
            kind: "kind",
            package_name: "package_name",
            searchable: true,
            skill_id: "skill_id",
            status: "status",
            task_family: "task_family",
            unavailable_reason: "unavailable_reason",
            updated_at: "updated_at",
            uuid: "uuid",
        };

        server
            .mockEndpoint()
            .get("/agents/agent_uuid/skills/skill_uuid")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agent.skill.get("agent_uuid", "skill_uuid");
        expect(response).toEqual({
            agentVersions: ["agent_versions"],
            createdAt: "created_at",
            currentVersion: 1,
            kind: "kind",
            packageName: "package_name",
            searchable: true,
            skillId: "skill_id",
            status: "status",
            taskFamily: "task_family",
            unavailableReason: "unavailable_reason",
            updatedAt: "updated_at",
            uuid: "uuid",
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/agents/agent_uuid/skills/skill_uuid")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.get("agent_uuid", "skill_uuid");
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/agents/agent_uuid/skills/skill_uuid")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.get("agent_uuid", "skill_uuid");
        }).rejects.toThrow(Zep.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/agents/agent_uuid/skills/skill_uuid")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.get("agent_uuid", "skill_uuid");
        }).rejects.toThrow(Zep.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/agents/agent_uuid/skills/skill_uuid")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.get("agent_uuid", "skill_uuid");
        }).rejects.toThrow(Zep.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/agents/agent_uuid/skills/skill_uuid")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.skill.get("agent_uuid", "skill_uuid");
        }).rejects.toThrow(Zep.ServiceUnavailableError);
    });
});
