// This file was auto-generated by Fern from our API Definition.

import * as Zep from "../../src/api/index";
import { ZepClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ContextClient", () => {
    test("list_context_templates (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { templates: [{ template: "template", template_id: "template_id", uuid: "uuid" }] };

        server.mockEndpoint().get("/context-templates").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.context.listContextTemplates();
        expect(response).toEqual({
            templates: [
                {
                    template: "template",
                    templateId: "template_id",
                    uuid: "uuid",
                },
            ],
        });
    });

    test("list_context_templates (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/context-templates").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.context.listContextTemplates();
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("list_context_templates (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/context-templates").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.context.listContextTemplates();
        }).rejects.toThrow(Zep.InternalServerError);
    });

    test("create_context_template (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { template: "template", template_id: "template_id" };
        const rawResponseBody = { template: "template", template_id: "template_id", uuid: "uuid" };

        server
            .mockEndpoint()
            .post("/context-templates")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.context.createContextTemplate({
            template: "template",
            templateId: "template_id",
        });
        expect(response).toEqual({
            template: "template",
            templateId: "template_id",
            uuid: "uuid",
        });
    });

    test("create_context_template (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { template: "x", template_id: "template_id" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/context-templates")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.context.createContextTemplate({
                template: "x",
                templateId: "template_id",
            });
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("create_context_template (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { template: "x", template_id: "template_id" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/context-templates")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.context.createContextTemplate({
                template: "x",
                templateId: "template_id",
            });
        }).rejects.toThrow(Zep.InternalServerError);
    });

    test("get_context_template (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { template: "template", template_id: "template_id", uuid: "uuid" };

        server
            .mockEndpoint()
            .get("/context-templates/template_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.context.getContextTemplate("template_id");
        expect(response).toEqual({
            template: "template",
            templateId: "template_id",
            uuid: "uuid",
        });
    });

    test("get_context_template (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/context-templates/template_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.context.getContextTemplate("template_id");
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("get_context_template (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/context-templates/template_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.context.getContextTemplate("template_id");
        }).rejects.toThrow(Zep.NotFoundError);
    });

    test("get_context_template (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/context-templates/template_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.context.getContextTemplate("template_id");
        }).rejects.toThrow(Zep.InternalServerError);
    });

    test("update_context_template (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { template: "template" };
        const rawResponseBody = { template: "template", template_id: "template_id", uuid: "uuid" };

        server
            .mockEndpoint()
            .put("/context-templates/template_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.context.updateContextTemplate("template_id", {
            template: "template",
        });
        expect(response).toEqual({
            template: "template",
            templateId: "template_id",
            uuid: "uuid",
        });
    });

    test("update_context_template (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { template: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/context-templates/template_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.context.updateContextTemplate("template_id", {
                template: "x",
            });
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("update_context_template (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { template: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/context-templates/template_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.context.updateContextTemplate("template_id", {
                template: "x",
            });
        }).rejects.toThrow(Zep.NotFoundError);
    });

    test("update_context_template (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { template: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/context-templates/template_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.context.updateContextTemplate("template_id", {
                template: "x",
            });
        }).rejects.toThrow(Zep.InternalServerError);
    });

    test("delete_context_template (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/context-templates/template_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.context.deleteContextTemplate("template_id");
        expect(response).toEqual({
            message: "message",
        });
    });

    test("delete_context_template (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/context-templates/template_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.context.deleteContextTemplate("template_id");
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("delete_context_template (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/context-templates/template_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.context.deleteContextTemplate("template_id");
        }).rejects.toThrow(Zep.NotFoundError);
    });

    test("delete_context_template (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/context-templates/template_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.context.deleteContextTemplate("template_id");
        }).rejects.toThrow(Zep.InternalServerError);
    });
});
