// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";

export const RelationListRequestKindItem: core.serialization.Schema<
    serializers.agent.skill.RelationListRequestKindItem.Raw,
    Zep.agent.skill.RelationListRequestKindItem
> = core.serialization.enum_([
    "composes",
    "requires",
    "conflicts_with",
    "supersedes",
    "related",
    "uses_tool",
    "uses_environment",
    "supported_by",
    "contradicted_by",
    "supersedes_version",
    "applied_in",
]);

export declare namespace RelationListRequestKindItem {
    export type Raw =
        | "composes"
        | "requires"
        | "conflicts_with"
        | "supersedes"
        | "related"
        | "uses_tool"
        | "uses_environment"
        | "supported_by"
        | "contradicted_by"
        | "supersedes_version"
        | "applied_in";
}
