// This file was auto-generated by Fern from our API Definition.

import type * as Zep from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface AgentVerifierListRequest {
    /** Page size */
    limit?: number;
    /** Page cursor */
    cursor?: string;
    /** Filters to an exact immutable verifier class. */
    class?: string;
    /** Filters to registrations bound to this exact principal identifier. */
    principalId?: string;
    /** Filters to registrations bound to this principal type. */
    principalType?: string;
    /** Filters to active or revoked registrations. Omit to include both. */
    status?: Zep.AgentVerifierStatus;
    /** Filters to an exact developer-assigned verifier identifier. */
    verifierId?: string;
}
