/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Zep from "../../../../api";
import * as core from "../../../../core";
import { ModelsUser } from "../../../types/ModelsUser";

export const Response: core.serialization.Schema<serializers.user.listOrdered.Response.Raw, Zep.ModelsUser[]> =
    core.serialization.list(ModelsUser);

export declare namespace Response {
    type Raw = ModelsUser.Raw[];
}
