// This file was auto-generated by Fern from our API Definition.

import { BatchClient } from "./api/resources/batch/client/Client.js";
import { ContextClient } from "./api/resources/context/client/Client.js";
import { GraphClient } from "./api/resources/graph/client/Client.js";
import { LookupClient } from "./api/resources/lookup/client/Client.js";
import { ProjectClient } from "./api/resources/project/client/Client.js";
import { TaskClient } from "./api/resources/task/client/Client.js";
import { ThreadClient } from "./api/resources/thread/client/Client.js";
import { UserClient } from "./api/resources/user/client/Client.js";
import { UserGroupClient } from "./api/resources/userGroup/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace ZepClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ZepClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ZepClient.Options>;
    protected _batch: BatchClient | undefined;
    protected _context: ContextClient | undefined;
    protected _graph: GraphClient | undefined;
    protected _lookup: LookupClient | undefined;
    protected _project: ProjectClient | undefined;
    protected _task: TaskClient | undefined;
    protected _thread: ThreadClient | undefined;
    protected _userGroup: UserGroupClient | undefined;
    protected _user: UserClient | undefined;

    constructor(options: ZepClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get batch(): BatchClient {
        return (this._batch ??= new BatchClient(this._options));
    }

    public get context(): ContextClient {
        return (this._context ??= new ContextClient(this._options));
    }

    public get graph(): GraphClient {
        return (this._graph ??= new GraphClient(this._options));
    }

    public get lookup(): LookupClient {
        return (this._lookup ??= new LookupClient(this._options));
    }

    public get project(): ProjectClient {
        return (this._project ??= new ProjectClient(this._options));
    }

    public get task(): TaskClient {
        return (this._task ??= new TaskClient(this._options));
    }

    public get thread(): ThreadClient {
        return (this._thread ??= new ThreadClient(this._options));
    }

    public get userGroup(): UserGroupClient {
        return (this._userGroup ??= new UserGroupClient(this._options));
    }

    public get user(): UserClient {
        return (this._user ??= new UserClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
