// This file was auto-generated by Fern from our API Definition.

import * as Zep from "../../../src/api/index";
import { ZepClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("EdgeClient", () => {
    test("get_by_graph_id (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = [
            {
                attributes: { key: "value" },
                created_at: "created_at",
                episodes: ["episodes"],
                expired_at: "expired_at",
                fact: "fact",
                invalid_at: "invalid_at",
                name: "name",
                relevance: 1.1,
                scope: "scope",
                score: 1.1,
                selection_rank: 1,
                source_node_uuid: "source_node_uuid",
                target_node_uuid: "target_node_uuid",
                uuid: "uuid",
                valid_at: "valid_at",
            },
        ];

        server
            .mockEndpoint()
            .post("/graph/edge/graph/graph_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.graph.edge.getByGraphId("graph_id", {});
        expect(response).toEqual([
            {
                attributes: {
                    key: "value",
                },
                createdAt: "created_at",
                episodes: ["episodes"],
                expiredAt: "expired_at",
                fact: "fact",
                invalidAt: "invalid_at",
                name: "name",
                relevance: 1.1,
                scope: "scope",
                score: 1.1,
                selectionRank: 1,
                sourceNodeUuid: "source_node_uuid",
                targetNodeUuid: "target_node_uuid",
                uuid: "uuid",
                validAt: "valid_at",
            },
        ]);
    });

    test("get_by_graph_id (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/graph/edge/graph/graph_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.graph.edge.getByGraphId("graph_id", {});
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("get_by_graph_id (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/graph/edge/graph/graph_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.graph.edge.getByGraphId("graph_id", {});
        }).rejects.toThrow(Zep.InternalServerError);
    });

    test("get_by_user_id (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = [
            {
                attributes: { key: "value" },
                created_at: "created_at",
                episodes: ["episodes"],
                expired_at: "expired_at",
                fact: "fact",
                invalid_at: "invalid_at",
                name: "name",
                relevance: 1.1,
                scope: "scope",
                score: 1.1,
                selection_rank: 1,
                source_node_uuid: "source_node_uuid",
                target_node_uuid: "target_node_uuid",
                uuid: "uuid",
                valid_at: "valid_at",
            },
        ];

        server
            .mockEndpoint()
            .post("/graph/edge/user/user_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.graph.edge.getByUserId("user_id", {});
        expect(response).toEqual([
            {
                attributes: {
                    key: "value",
                },
                createdAt: "created_at",
                episodes: ["episodes"],
                expiredAt: "expired_at",
                fact: "fact",
                invalidAt: "invalid_at",
                name: "name",
                relevance: 1.1,
                scope: "scope",
                score: 1.1,
                selectionRank: 1,
                sourceNodeUuid: "source_node_uuid",
                targetNodeUuid: "target_node_uuid",
                uuid: "uuid",
                validAt: "valid_at",
            },
        ]);
    });

    test("get_by_user_id (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/graph/edge/user/user_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.graph.edge.getByUserId("user_id", {});
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("get_by_user_id (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/graph/edge/user/user_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.graph.edge.getByUserId("user_id", {});
        }).rejects.toThrow(Zep.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            attributes: { key: "value" },
            created_at: "created_at",
            episodes: ["episodes"],
            expired_at: "expired_at",
            fact: "fact",
            invalid_at: "invalid_at",
            name: "name",
            relevance: 1.1,
            scope: "scope",
            score: 1.1,
            selection_rank: 1,
            source_node_uuid: "source_node_uuid",
            target_node_uuid: "target_node_uuid",
            uuid: "uuid",
            valid_at: "valid_at",
        };

        server.mockEndpoint().get("/graph/edge/uuid").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.graph.edge.get("uuid");
        expect(response).toEqual({
            attributes: {
                key: "value",
            },
            createdAt: "created_at",
            episodes: ["episodes"],
            expiredAt: "expired_at",
            fact: "fact",
            invalidAt: "invalid_at",
            name: "name",
            relevance: 1.1,
            scope: "scope",
            score: 1.1,
            selectionRank: 1,
            sourceNodeUuid: "source_node_uuid",
            targetNodeUuid: "target_node_uuid",
            uuid: "uuid",
            validAt: "valid_at",
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/graph/edge/uuid").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.graph.edge.get("uuid");
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/graph/edge/uuid").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.graph.edge.get("uuid");
        }).rejects.toThrow(Zep.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/graph/edge/uuid").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.graph.edge.get("uuid");
        }).rejects.toThrow(Zep.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/graph/edge/uuid")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.graph.edge.delete("uuid");
        expect(response).toEqual({
            message: "message",
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/graph/edge/uuid")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.graph.edge.delete("uuid");
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/graph/edge/uuid")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.graph.edge.delete("uuid");
        }).rejects.toThrow(Zep.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/graph/edge/uuid")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.graph.edge.delete("uuid");
        }).rejects.toThrow(Zep.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            attributes: { key: "value" },
            created_at: "created_at",
            episodes: ["episodes"],
            expired_at: "expired_at",
            fact: "fact",
            invalid_at: "invalid_at",
            name: "name",
            relevance: 1.1,
            scope: "scope",
            score: 1.1,
            selection_rank: 1,
            source_node_uuid: "source_node_uuid",
            target_node_uuid: "target_node_uuid",
            uuid: "uuid",
            valid_at: "valid_at",
        };

        server
            .mockEndpoint()
            .patch("/graph/edge/uuid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.graph.edge.update("uuid");
        expect(response).toEqual({
            attributes: {
                key: "value",
            },
            createdAt: "created_at",
            episodes: ["episodes"],
            expiredAt: "expired_at",
            fact: "fact",
            invalidAt: "invalid_at",
            name: "name",
            relevance: 1.1,
            scope: "scope",
            score: 1.1,
            selectionRank: 1,
            sourceNodeUuid: "source_node_uuid",
            targetNodeUuid: "target_node_uuid",
            uuid: "uuid",
            validAt: "valid_at",
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/graph/edge/uuid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.graph.edge.update("uuid");
        }).rejects.toThrow(Zep.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/graph/edge/uuid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.graph.edge.update("uuid");
        }).rejects.toThrow(Zep.NotFoundError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/graph/edge/uuid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.graph.edge.update("uuid");
        }).rejects.toThrow(Zep.InternalServerError);
    });
});
