/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool";
import * as Zep from "../../../src/api/index";
import { ZepClient } from "../../../src/Client";

describe("Observation", () => {
    test("get_by_graph_id", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = [
            {
                attributes: { key: "value" },
                created_at: "created_at",
                end_at: "end_at",
                episode_ids: ["episode_ids"],
                labels: ["labels"],
                latest_evidence_at: "latest_evidence_at",
                name: "name",
                relevance: 1.1,
                score: 1.1,
                selection_rank: 1,
                start_at: "start_at",
                summary: "summary",
                uuid: "uuid",
            },
        ];
        server
            .mockEndpoint()
            .post("/graph/observation/graph/graph_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.graph.observation.getByGraphId("graph_id", {});
        expect(response).toEqual([
            {
                attributes: {
                    key: "value",
                },
                createdAt: "created_at",
                endAt: "end_at",
                episodeIds: ["episode_ids"],
                labels: ["labels"],
                latestEvidenceAt: "latest_evidence_at",
                name: "name",
                relevance: 1.1,
                score: 1.1,
                selectionRank: 1,
                startAt: "start_at",
                summary: "summary",
                uuid: "uuid",
            },
        ]);
    });

    test("get_by_user_id", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = [
            {
                attributes: { key: "value" },
                created_at: "created_at",
                end_at: "end_at",
                episode_ids: ["episode_ids"],
                labels: ["labels"],
                latest_evidence_at: "latest_evidence_at",
                name: "name",
                relevance: 1.1,
                score: 1.1,
                selection_rank: 1,
                start_at: "start_at",
                summary: "summary",
                uuid: "uuid",
            },
        ];
        server
            .mockEndpoint()
            .post("/graph/observation/user/user_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.graph.observation.getByUserId("user_id", {});
        expect(response).toEqual([
            {
                attributes: {
                    key: "value",
                },
                createdAt: "created_at",
                endAt: "end_at",
                episodeIds: ["episode_ids"],
                labels: ["labels"],
                latestEvidenceAt: "latest_evidence_at",
                name: "name",
                relevance: 1.1,
                score: 1.1,
                selectionRank: 1,
                startAt: "start_at",
                summary: "summary",
                uuid: "uuid",
            },
        ]);
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new ZepClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            attributes: { key: "value" },
            created_at: "created_at",
            end_at: "end_at",
            episode_ids: ["episode_ids"],
            labels: ["labels"],
            latest_evidence_at: "latest_evidence_at",
            name: "name",
            relevance: 1.1,
            score: 1.1,
            selection_rank: 1,
            start_at: "start_at",
            summary: "summary",
            uuid: "uuid",
        };
        server
            .mockEndpoint()
            .get("/graph/observation/uuid")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.graph.observation.get("uuid");
        expect(response).toEqual({
            attributes: {
                key: "value",
            },
            createdAt: "created_at",
            endAt: "end_at",
            episodeIds: ["episode_ids"],
            labels: ["labels"],
            latestEvidenceAt: "latest_evidence_at",
            name: "name",
            relevance: 1.1,
            score: 1.1,
            selectionRank: 1,
            startAt: "start_at",
            summary: "summary",
            uuid: "uuid",
        });
    });
});
